//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEATURE
    {
        public int FEATUREID { get; set; }
        public string NAME { get; set; }
        public string FEATUREXML { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public Nullable<int> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<int> MODULE { get; set; }
        public string MODULENAME { get; set; }
        public string ACTION { get; set; }
        public string CONTROLLER { get; set; }
        public string AREA { get; set; }
    }
}
