//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEATUREASSIGN
    {
        public int ID { get; set; }
        public Nullable<int> ENTITY { get; set; }
        public Nullable<int> ENTITYID { get; set; }
        public Nullable<int> ASSIGNTYPE { get; set; }
        public Nullable<int> ASSIGNUSER { get; set; }
        public Nullable<System.DateTime> ASSIGNEDDATE { get; set; }
        public Nullable<int> ASSIGNEDBY { get; set; }
    }
}
