//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRIDVIEW
    {
        public int VIEWSEQNO { get; set; }
        public string VIEWNAME { get; set; }
        public string TABLENAME { get; set; }
        public string ALIASTABLENAME { get; set; }
        public string PRIMARYCOLUMN { get; set; }
        public Nullable<int> FEATUREID { get; set; }
        public string SELECTEDCOLUMNS { get; set; }
        public string ALIASCOLUMNS { get; set; }
        public string COLUMNSTYPE { get; set; }
        public string COLUMNWIDTHS { get; set; }
        public string APPQUERY { get; set; }
        public string WHERECONDITION { get; set; }
        public string QUERY { get; set; }
        public Nullable<bool> FITLERBYTENANT { get; set; }
        public Nullable<bool> ISSYSTEMVIEW { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public Nullable<int> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<int> MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
    }
}
