//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPMS.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SUPMSEntities : DbContext
    {
        public SUPMSEntities()
            : base("name=SUPMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FEATUREASSIGN> FEATUREASSIGNs { get; set; }
        public virtual DbSet<FEATUREASSIGN_HISTORY> FEATUREASSIGN_HISTORY { get; set; }
        public virtual DbSet<FEATURE> FEATURES { get; set; }
        public virtual DbSet<GRIDVIEW> GRIDVIEWS { get; set; }
        public virtual DbSet<ROLE> ROLES { get; set; }
        public virtual DbSet<USERGROUPMAPPING> USERGROUPMAPPINGs { get; set; }
        public virtual DbSet<USERGROUP> USERGROUPS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
