//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERGROUPMAPPING
    {
        public int ID { get; set; }
        public Nullable<int> USERGROUPSEQNO { get; set; }
        public Nullable<int> USERID { get; set; }
    }
}
