//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string EMAILADDRESS { get; set; }
        public string MOBILE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> ROLEID { get; set; }
        public string USERTYPE { get; set; }
        public string PROFILEPICPATH { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public Nullable<int> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<int> MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
    }
}
