//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERGROUP
    {
        public int USERGROUPSEQNO { get; set; }
        public string GROUPNAME { get; set; }
        public string GROUPDESCRIPTION { get; set; }
        public Nullable<int> GROUPOWNER { get; set; }
        public Nullable<int> COMPANYID { get; set; }
        public Nullable<int> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<int> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
    }
}
